defaults:
  - image_generator: dreambooth
  - dataset_generator: tests

data_dir: ${root_dir}/dataset
root_dir:  ${hydra:runtime.cwd}
batch_size: 10

labels_file: ${root_dir}/list_of_cheese.txt

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true
